- name: Install MariaDB
  hosts: all
  gather_facts: true
  become: true

  vars:
    target_user: kier

  tasks:
    - name: Install MariaDB server
      ansible.builtin.apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Ensure MariaDB service is running
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
      loop:
        - test_d1
        - test_d2
        - test_d3